//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedyBI_API.Models
{
    using System;
    using System.Collections.Generic;
    using SpeedyBI_API.Tools;
    
    public partial class loginUsers
    {
        public int idUser { get; set; }
        public string Usuario { get; set; }
        public string NombreUser { get; set; }
        public string  Contraseña { get; set; }
        public Nullable<System.DateTime> UltimaConexion { get; set; }
    }
}
